.TH COLORQUANT 3 "August 14, 1989"
.UC 4
.SH NAME
colorquant \- variance-based color quantization
.SH SYNOPSIS
int colorquant(red, green, blue, npix, colormap, colors, bits, rgbmap, fast)
.br
unsigned char *red, *green, *blue;
.br
unsigned long npix;
.br
unsigned char *colormap[3];
.br
int colors, bits;
.br
unsigned char *rgbmap;
.br
int fast;
.SH DESCRIPTION
.I Colorquant 
performs variance-based color quantization on a given image.
A representative colormap
and a table for performing RGB to colormap index mapping are computed.  The
number of colors to which the image was quantized (the total number
of colormap entries computed) is returned.
The arguments to
.I colorquant 
are:
.TP
.B red, green, blue
The red, green and blue channels of the image.  The ith pixel is represented
as the RGB triple (\fBred\fR[i], \fBgreen\fR[i], \fBblue\fR[i]).  These
arrays usually contain values which have been 'prequantized' (see below).
.TP
.B npix
The length, in bytes, of the \fBred\fR, \fBgreen\fR and \fBblue\fR arrays.
In other words, the total number of pixels in the image.
.TP
.B colormap
Points to a pre-allocated, three-channel colormap.  These arrays will be
filled with the colormap values computed by the variance-based color
quantization algorithm.  \fBcolormap\fR[0][i], \fBcolormap\fR[1][i], and
\fBcolormap\fR[2][i] are, respectively, the red, green and blue components
of the ith colormap entry.
.TP
.B colors
The number of pre-allocated colormap entries.  The image will be quantized to
at most this many colors.
.TP
.B bits
The number of significant bits in each entry of the \fBred\fR, \fBgreen\fR and
\fBblue\fR arrays.  Normally, the red, green and blue arrays contain
values which have been prequantized from eight to a lower number of
significant bits.
Five significant bits usually represents a good tradeoff between image quality
and running time.  Anything above six significant bits will likely lead to
excessive paging, as the size of \fBrgbmap\fR and the internal histogram are
proportional to (2^\fBbits\fR)^3. 
.TP
.B rgbmap
A pointer to an array of unsigned chars of size (2^\fBbits\fR)^3.
This array is used
to map from pixels to colormap entries.  The prequantized red, green
and blue components of a pixel are used as an index into this array
to retrieve the colormap index which should be used to represent the
pixel.  The array is indexed as:
.ce 1
colorindex = \fBrgbmap\fR[(((r << \fBbits\fR) | g) << \fBbits\fR) | b];
where r, g, and b are the prequantized red, green and blue components of
the pixel in question.
.TP
.B fast
If non-zero, the construction of rgbmap will be relatively fast.  If
zero, \fBrgbmap\fR will be built slowly but more accurately.  In most cases,
the error introduced by the 'fast' approximation is barely noticeable.
.SH AUTHOR
Craig Kolb
.SH REFERENCE
Wan, Wong, and Prusinkiewicz,
\fIAn Algorithm for Multidimensional Data Clustering,\fR
Transactions on Mathematical Software, Vol. 14 #2 (June, 1988), pp. 153-162.
